name: "Create Table Form"
description: "Create table issue form"

labels: [feature: table creation, role: back end, size: 2pt]
title: Create Table [name of table]
body:
  - type: markdown
    attributes:
      value: |
        Please see the [wiki page](https://github.com/hackforla/peopledepot/wiki/Create-Table-issues-data-gathering-workflow) for instructions.
  - type: textarea
    id: overview
    attributes:
      label: Overview
      description: Clearly state the purpose of this issue in 2 sentences or less
      value: |
        We need to create the [name of table] table so that we can update a shared data store across hackforla.org, vrms, civictechjobs, and tables (onboarding) project.

        #### Details

        A table and a model are the same thing
    validations:
      required: true
  - type: textarea
    id: action-items
    attributes:
      label: Action Items
      description: "List the research to be done, or the steps to be completed. Note: If the steps can be divided into tasks for more than one person, we recommend dividing it up into separate issues, or assigning it as a pair programming task."
      value: |
        - [ ] identify if table has a description (see spreadsheet under Resources)
          - [ ] if not, reach out to PD leads
        - [ ] identify and document (below) what the **data fields** are and make sure the ERD and spreadsheets match (see Resources)
        - [ ] identify and document  (below) what **other tables are associated** and make sure the ERD and spreadsheets match (see Resources)
        - [ ] create a single model in Django (defining schema)
        - [ ] Write a test for the relationships this model will have with other models (e.g., creating a user and assigning them a set of permissions on a project).
        - [ ] Write an API end point
        - [ ] write API unit tests
        - [ ] Document the endpoint
    validations:
      required: true
  - type: textarea
    id: resources-instructions
    attributes:
      label: "Resources/Instructions"
      description: "Provide links to resources or instructions that may help with this issue. This can include files to be worked on, external sites with solutions, documentation, etc."
      value: |
        - See [People Depot Resources wiki page](https://github.com/hackforla/peopledepot/wiki/Resources-and-Links) for links
          - ERD
          - Table and Field Definitions
          - API Endpoint
    validations:
      required: true
  - type: textarea
    id: table-description
    attributes:
      label: Description
  - type: textarea
    id: table-data
    attributes:
      label: Data Fields
      value: |
        1. Copied from spreadsheet and checked off according to ERD. Data fields are bolded and relation fields are not. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)
           - [ ] [name] - [type]

        1. In ERD only (having items here indicates a mismatch, which requires a review)
           - [name] - [type]
  - type: textarea
    id: table-associations
    attributes:
      label: Associated Tables
      value: |
        1. Copied from spreadsheet and checked off according to ERD (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)
           - [x] [other_table] ([relationship])

        1. In ERD only (having items here indicates a mismatch, which requires a review)
           - None
