admin_global = "adminGlobal"
admin_project = "adminProject"
practice_lead_project = "practiceLeadProject"
member_project = "memberProject"
field_permissions_csv_file = "core/api/field_permissions.csv"
profile_permissions_csv_file = "core/api/profile_permissions.csv"
