admin_global = "adminGlobal"
admin_project = "adminProject"
practice_lead_project = "practiceLeadProject"
member_project = "memberProject"
field_permissions_csv_file = "core/api/project_field_permissions.csv"
