# pull official base image
FROM python:3.10-alpine

# set work directory
WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPYCACHEPREFIX=/root/.cache/pycache/
ENV DJANGO_SETTINGS_MODULE=peopledepot.settings_aws

# install system dependencies
RUN \
  --mount=type=cache,target=/var/cache/apk \
  --mount=type=cache,target=/etc/apk/cache \
  apk add \
  'graphviz=~12'

# install font for graphviz
COPY Roboto-Regular.ttf /root/.fonts/
RUN fc-cache -f

# install dependencies
COPY ./requirements-aws.txt .
# hadolint ignore=DL3042
RUN \
  --mount=type=cache,target=/root/.cache \
  pip install uv==0.1.15 \
  && uv pip install --system -r requirements-aws.txt

# copy project
COPY . .

# collect static files
RUN python manage.py collectstatic --noinput

# copy and configure entrypoint
COPY ./entrypoint-aws.sh .
RUN sed -i 's/\r$//g' /usr/src/app/entrypoint-aws.sh \
  && chmod +x /usr/src/app/entrypoint-aws.sh

# Expose the gunicorn port
EXPOSE 8000

ENTRYPOINT ["/usr/src/app/entrypoint-aws.sh"]
