# Generated by Django 4.0.6 on 2022-08-12 22:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_squashed_0007_user_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed at')),
                ('github_org_id', models.CharField(blank=True, help_text='Can be retrieved from gh api with the following: curl -H "Authorization: token [gh_PAT]" https://api.github.com/orgs/[org]', max_length=8)),
                ('github_primary_repo_id', models.CharField(blank=True, help_text='Can be retrieved from gh api with the following: curl -H "Authorization: token [gh_PAT]" https://api.github.com/repos/[org]/[repo]', max_length=9)),
                ('github_primary_url', models.CharField(blank=True, max_length=255)),
                ('hide', models.BooleanField(default=True)),
                ('slack_url', models.URLField(blank=True)),
                ('google_drive_url', models.URLField(blank=True)),
                ('google_drive_id', models.CharField(blank=True, max_length=255)),
                ('hfla_website_url', models.URLField(blank=True)),
                ('image_logo', models.URLField(blank=True)),
                ('image_hero', models.URLField(blank=True)),
                ('image_icon', models.URLField(blank=True)),
                ('readme_url', models.URLField(blank=True)),
                ('wiki_url', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
