# Generated by Django 4.0.10 on 2023-11-01 16:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_programseed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expirement',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('quanity', models.IntegerField(verbose_name='Expirement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
