# Generated by Django 4.0.6 on 2022-07-28 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_status',
        ),
    ]
