# Generated by Django 4.0.7 on 2022-09-21 23:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recurringevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorPartner',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('partner_name', models.CharField(max_length=255)),
                ('partner_logo', models.URLField(blank=True)),
                ('is_active', models.BooleanField(null=True)),
                ('url', models.CharField(max_length=255)),
                ('is_sponsor', models.BooleanField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
