# Generated by Django 4.0.8 on 2022-11-18 18:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sponsorpartner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('question', models.CharField(max_length=255, unique=True)),
                ('answer', models.CharField(blank=True, max_length=255)),
                ('tool_tip_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='sponsorpartner',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='Faq_viewed',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('read', models.DateTimeField(auto_now=True, null=True, verbose_name='Read')),
                ('faq', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.faq')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
