# Generated by Django 4.0.7 on 2022-09-26 20:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_sponsorpartner_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('question', models.CharField(max_length=255, null=True, unique=True)),
                ('answer', models.CharField(max_length=255)),
                ('tool_tip_name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
