# Generated by Django 4.0.6 on 2022-07-29 23:09

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(blank=True, default='America/Los_Angeles', use_pytz=False),
        ),
    ]
