# Generated by Django 4.0.7 on 2022-09-25 03:36

from django.db import migrations


def add_data(apps, schema_editor):
    from ..scripts import userstatus_seed

    userstatus_seed.run()


def delete_data(apps, schema_editor):
    UserStatus = apps.get_model("core", "UserStatus")
    UserStatus.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_userstatus_user_status"),
    ]

    operations = [migrations.RunPython(add_data, delete_data)]
