# Generated by Django 4.0.7 on 2022-09-29 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_faq_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq_viewed',
            name='faq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.faq'),
        ),
    ]
