# Generated by Django 4.0.8 on 2022-11-19 17:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq_viewed',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('read', models.DateTimeField(auto_now=True, null=True, verbose_name='Read')),
                ('faq', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.faq')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
