# Generated by Django 4.0.7 on 2022-09-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='faq',
            name='tool_tip_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
