# Generated by Django 4.0.7 on 2022-09-30 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_faq_viewed_faq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SponsorPartner',
        ),
    ]
