# Generated by Django 4.0.8 on 2022-10-21 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_sponsorpartner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq_viewed',
            name='project',
        ),
    ]
