# Generated by Django 4.0.10 on 2023-02-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location_nm',
        ),
        migrations.RemoveField(
            model_name='location',
            name='phone_num',
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='phone',
            field=models.CharField(default='null', max_length=15, verbose_name='Phone number'),
            preserve_default=False,
        ),
    ]
