# Generated by Django 4.0.10 on 2023-06-15 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_technology'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name_plural': 'Technologies'},
        ),
    ]
