# Generated by Django 4.0.8 on 2022-10-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_faq_viewed_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq_viewed',
            name='read',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at'),
        ),
    ]
