# Generated by Django 4.0.8 on 2022-10-21 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_faq_viewed_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq_viewed',
            name='faq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.faq', to_field='question'),
        ),
    ]
