# Generated by Django 4.0.10 on 2023-07-20 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_technology'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
