# Generated by Django 4.0.8 on 2022-10-31 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_faq_viewed_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq_viewed',
            name='read',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last read'),
        ),
    ]
