# Generated by Django 4.0.8 on 2022-11-07 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_faq_viewed_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq_viewed',
            name='faq',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.faq'),
        ),
        migrations.AlterField(
            model_name='faq_viewed',
            name='read',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Read'),
        ),
    ]
