# Generated by Django 4.0.10 on 2023-09-27 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_permissiontype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='github_primary_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='google_drive_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='hfla_website_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='readme_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='slack_url',
        ),
        migrations.RemoveField(
            model_name='project',
            name='wiki_url',
        ),
    ]
