# Generated by Django 4.0.10 on 2023-10-25 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_delete_language'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecurringEvent',
            new_name='Event',
        ),
    ]
