# Generated by Django 4.0.10 on 2023-11-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0019_stackelementtype")]

    operations = [
        migrations.RenameField(
            model_name="sponsorpartner",
            old_name="is_sponsor",
            new_name="is_org_sponsor",
        ),
        migrations.AddField(
            model_name="sponsorpartner",
            name="is_org_partner",
            field=models.BooleanField(null=True),
        ),
    ]
