# Generated by Django 4.0.10 on 2023-12-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programarea',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
