# Generated by Django 4.0.10 on 2023-12-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_rename_is_sponsor_sponsorpartner_is_org_partner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programarea',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
