# Generated by Django 4.2.11 on 2024-05-09 02:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_sdg"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SponsorPartner",
            new_name="Affiliate",
        ),
        migrations.CreateModel(
            name="Affiliation",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ended at"
                    ),
                ),
                ("is_sponsor", models.BooleanField(null=True)),
                ("is_partner", models.BooleanField(null=True)),
                (
                    "affiliate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.affiliate"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.project"
                    ),
                ),
            ],
            options={
                "db_table": "project_affiliate_xref",
            },
        ),
        migrations.AddConstraint(
            model_name="affiliation",
            constraint=models.UniqueConstraint(
                fields=("project", "affiliate"), name="unique_project_affiliate"
            ),
        ),
    ]
