# Generated by Django 4.0.10 on 2024-03-29 00:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_sdg'),
    ]

    operations = [
        migrations.CreateModel(
            name='StackElement',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('logo', models.URLField(blank=True)),
                ('active', models.BooleanField(null=True)),
                ('stack_element_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stackelementtype')),
            ],
            options={
                'verbose_name_plural': 'Stack Elements',
            },
        ),
        migrations.DeleteModel(
            name='Technology',
        ),
    ]
