# Generated by Django 4.0.10 on 2024-03-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_sdg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programarea',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
