# Generated by Django 4.2.11 on 2024-06-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_rename_sponsorpartner_affiliate_affiliation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="could_attend",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="event",
            name="must_attend",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="event",
            name="should_attend",
            field=models.JSONField(default=list),
        ),
    ]
