# Generated by Django 4.0.10 on 2024-04-12 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_stackelement_delete_technology'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stackelement',
            old_name='stack_element_type',
            new_name='element_type',
        ),
    ]
