# Generated by Django 4.2.11 on 2024-07-03 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_userpermissions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpermissions",
            name="practice_area",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.practicearea",
            ),
        ),
    ]
