# Generated by Django 4.2.11 on 2024-07-12 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_userpermissions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="permissiontype",
            name="rank",
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name="permissiontype",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="userpermissions",
            name="practice_area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.practicearea",
            ),
        ),
        migrations.AlterField(
            model_name="userpermissions",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
