# Generated by Django 4.2.11 on 2024-09-06 21:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_permissiontype_rank_alter_permissiontype_name_and_more")
    ]

    operations = [
        migrations.CreateModel(
            name="StackElement",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField(blank=True)),
                ("logo", models.URLField(blank=True)),
                ("active", models.BooleanField(null=True)),
                (
                    "element_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.stackelementtype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Stack Elements",
            },
        ),
        migrations.DeleteModel(
            name="Technology",
        ),
    ]
