# Generated by Django 4.2.11 on 2024-07-05 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_alter_userpermissions_practice_area"),
    ]

    operations = [
        migrations.AddField(
            model_name="permissiontype",
            name="rank",
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="permissiontype",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="userpermissions",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
