# Generated by Django 4.2.11 on 2024-07-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_permissiontype_rank_alter_userpermissions_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permissiontype",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
