# Generated by Django 4.2.11 on 2024-09-24 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_socmajor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpermission",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.project",
            ),
        ),
    ]
