# Generated by Django 4.2.16 on 2025-03-06 05:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_projectprogramareaxref_project_program_areas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'project statuses',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='current_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.projectstatus'),
        ),
    ]
