# Generated by Django 4.2.16 on 2025-03-14 21:22

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_projectstatus_project_current_status'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', core.models.UserManager()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='gmail',
            new_name='email_gmail',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='email_intake',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='preferred_email',
            new_name='email_preferred',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='current_job_title',
            new_name='job_title_current_intake',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='target_job_title',
            new_name='job_title_target_intake',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='name_first',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='last_name',
            new_name='name_last',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.AddField(
            model_name='user',
            name='email_cognito',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='practice_area_primary',
            field=models.ManyToManyField(blank=True, related_name='primary_users', to='core.practicearea'),
        ),
        migrations.AddField(
            model_name='user',
            name='practice_area_secondary',
            field=models.ManyToManyField(blank=True, related_name='secondary_users', to='core.practicearea'),
        ),
        migrations.AddField(
            model_name='user',
            name='practice_area_target_intake',
            field=models.ManyToManyField(blank=True, related_name='target_intake_users', to='core.practicearea'),
        ),
    ]
