# Generated by Django 4.2.16 on 2025-03-08 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_rename_gmail_user_email_gmail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_intake',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email address'),
        ),
    ]
