# Generated by Django 4.2.16 on 2025-03-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_user_email_intake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_intake',
            field=models.EmailField(blank=True, default='noemail@example.com', max_length=254, verbose_name='Email address'),
            preserve_default=False,
        ),
    ]
