# Generated by Django 4.2.16 on 2025-05-30 19:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_referrertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referrer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('referrer_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.referrertype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='referrer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.referrer'),
        ),
    ]
