# Generated by Django 4.2.16 on 2025-06-12 07:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_referrer_user_referrer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocMinor',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('occ_code', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('soc_major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.socmajor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
