# Generated by Django 4.2.16 on 2025-08-19 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_leadershiptype_project_leadership_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='gmail',
            new_name='email_gmail',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='preferred_email',
            new_name='email_preferred',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='current_job_title',
            new_name='job_title_current_intake',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='target_job_title',
            new_name='job_title_target_intake',
        ),
        migrations.AddField(
            model_name='user',
            name='email_cognito',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='practice_area_primary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_users', to='core.practicearea'),
        ),
        migrations.AddField(
            model_name='user',
            name='practice_area_secondary',
            field=models.ManyToManyField(blank=True, related_name='secondary_users', to='core.practicearea'),
        ),
        migrations.AddField(
            model_name='user',
            name='practice_area_target_intake',
            field=models.ManyToManyField(blank=True, related_name='target_intake_users', to='core.practicearea'),
        ),
    ]
