# Generated by Django 5.2.4 on 2025-09-03 18:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_rename_gmail_user_email_gmail_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accomplishment",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("url", models.URLField()),
                ("accomplished_on", models.DateTimeField()),
                (
                    "project_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
