# Generated by Django 4.2.16 on 2025-09-11 15:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [('core', '0039_socminor')]

    operations = [
        migrations.CreateModel(
            name='ProjectUrl',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255)),
                ('external_id', models.CharField(blank=True, default='', max_length=255)),
                ('url', models.URLField(blank=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.project')),
                ('url_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.urltype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
