# Generated by Django 4.2.16 on 2025-10-24 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_projecturl'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionHistory',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('granted', models.DateTimeField(blank=True, null=True, verbose_name='Granted')),
                ('ended', models.DateTimeField(blank=True, null=True, verbose_name='Ended')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_permission_created_by', to=settings.AUTH_USER_MODEL)),
                ('permission_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.permissiontype')),
                ('practice_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.practicearea')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.project')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_permission_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_permission_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
