# Generated by Django 4.2.16 on 2025-10-21 04:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_projecturl'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStackElementXref',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_stack_elements', to='core.project')),
                ('stack_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stack_element_projects', to='core.stackelement')),
            ],
            options={
                'db_table': 'project_stack_element_xref',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='stack_elements',
            field=models.ManyToManyField(blank=True, related_name='projects', through='core.ProjectStackElementXref', to='core.stackelement'),
        ),
        migrations.AddConstraint(
            model_name='projectstackelementxref',
            constraint=models.UniqueConstraint(fields=('project', 'stack_element'), name='unique_project_stack_element'),
        ),
    ]
