# Generated by Django 4.2.16 on 2025-10-21 19:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_projectstackelementxref_project_stack_elements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlStatusType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='projecturl',
            name='url_status_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.urlstatustype'),
        ),
    ]
