# Generated by Django 4.2.16 on 2025-10-03 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_projectstackelementxref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stack_elements',
            field=models.ManyToManyField(blank=True, related_name='projects', through='core.ProjectStackElementXref', to='core.stackelement'),
        ),
        migrations.AlterField(
            model_name='projectstackelementxref',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_stack_elements', to='core.project'),
        ),
        migrations.AlterField(
            model_name='projectstackelementxref',
            name='stack_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stack_element_projects', to='core.stackelement'),
        ),
    ]
