# Generated by Django 5.2.4 on 2025-09-03 18:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_urlstatustype_projecturl_url_status_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accomplishment",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255,
                        db_comment="Title of the accomplishment"
                    )
                ),
                (
                    "description",
                    models.TextField(
                        db_comment="Detailed description of the accomplishment"
                    )
                ),
                (
                    "url",
                    models.URLField(
                        db_comment="URL link to the accomplishment"
                    )
                ),
                (
                    "accomplished_on",
                    models.DateTimeField(
                        db_comment="Date when the accomplishment was achieved"
                    )
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accomplishments",
                        to="core.project",
                        db_comment="Project this accomplishment belongs to"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name='accomplishment',
            index=models.Index(fields=['project'], name='core_accomp_project_idx'),
        ),
        migrations.AddIndex(
            model_name='accomplishment',
            index=models.Index(fields=['accomplished_on'], name='core_accomp_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='accomplishment',
            constraint=models.UniqueConstraint(
                fields=['project', 'title'],
                name='unique_accomplishment_per_project'
            ),
        ),
    ]
