# Generated by Django 4.2.16 on 2025-10-24 18:44

from django.db import migrations, models
import timezone_field.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_urlstatustype_projecturl_url_status_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('time_zone', timezone_field.fields.TimeZoneField(use_pytz=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
