# Generated by Django 4.2.16 on 2025-10-13 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_urlstatustype'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecturl',
            name='url_status_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.urlstatustype'),
        ),
    ]
