# Generated by Django 4.2.16 on 2025-11-05 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCheck',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('result', models.BooleanField(help_text='Result of the check (Yes/No). Unknown if null.', null=True)),
                ('reminder_start', models.DateTimeField(blank=True, help_text='When reminders should start.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the check was completed.', null=True)),
                ('check_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_checks', to='core.checktype')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_checks', to='core.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_checks', to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'check_type'], name='core_userch_user_id_848c90_idx'), models.Index(fields=['org'], name='core_userch_org_id_454dae_idx'), models.Index(fields=['project'], name='core_userch_project_eb584f_idx')],
            },
        ),
    ]
