# Generated by Django 4.2.16 on 2025-11-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_usercheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercheck',
            name='completed_at',
            field=models.DateTimeField(blank=True, db_comment='Completion timestamp; NULL if pending.', help_text='When the check was completed.', null=True),
        ),
        migrations.AlterField(
            model_name='usercheck',
            name='reminder_start',
            field=models.DateTimeField(blank=True, db_comment='Timestamp when reminder workflow begins.', help_text='When reminders should start.', null=True),
        ),
        migrations.AlterField(
            model_name='usercheck',
            name='result',
            field=models.BooleanField(db_comment='Result of the check (Yes/No). Unknown if null.', help_text='Result of the check (Yes/No). Unknown if null.', null=True),
        ),
        migrations.AddConstraint(
            model_name='usercheck',
            constraint=models.UniqueConstraint(condition=models.Q(('completed_at__isnull', True), ('org__isnull', True), ('project__isnull', True)), fields=('user', 'check_type'), name='uniq_active_global_user_check'),
        ),
        migrations.AddConstraint(
            model_name='usercheck',
            constraint=models.UniqueConstraint(condition=models.Q(('completed_at__isnull', True), ('org__isnull', False)), fields=('user', 'check_type', 'org'), name='uniq_active_org_user_check'),
        ),
        migrations.AddConstraint(
            model_name='usercheck',
            constraint=models.UniqueConstraint(condition=models.Q(('completed_at__isnull', True), ('project__isnull', False)), fields=('user', 'check_type', 'project'), name='uniq_active_project_user_check'),
        ),
    ]
