# Generated by Django 4.2.16 on 2025-11-18 16:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [('core', '0044_usercheck_usercheck_uniq_global_user_check_and_more')]

    operations = [
        migrations.CreateModel(
            name='WinType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('display_text', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
