# Generated by Django 4.2.16 on 2025-11-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_usercheck_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usercheck',
            name='uniq_active_global_user_check',
        ),
        migrations.RemoveConstraint(
            model_name='usercheck',
            name='uniq_active_org_user_check',
        ),
        migrations.RemoveConstraint(
            model_name='usercheck',
            name='uniq_active_project_user_check',
        ),
        migrations.AddConstraint(
            model_name='usercheck',
            constraint=models.UniqueConstraint(condition=models.Q(('org__isnull', True), ('project__isnull', True)), fields=('user', 'check_type'), name='uniq_global_user_check'),
        ),
        migrations.AddConstraint(
            model_name='usercheck',
            constraint=models.UniqueConstraint(condition=models.Q(('org__isnull', False)), fields=('user', 'check_type', 'org'), name='uniq_org_user_check'),
        ),
        migrations.AddConstraint(
            model_name='usercheck',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', False)), fields=('user', 'check_type', 'project'), name='uniq_project_user_check'),
        ),
    ]
