# Generated by Django 4.2.16 on 2025-11-27 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [('core', '0046_socbroad')]

    operations = [
        migrations.CreateModel(
            name='Win',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('description', models.CharField(max_length=255)),
                ('can_use_photo', models.BooleanField(default=False)),
                ('practice_areas', models.ManyToManyField(blank=True, related_name='wins', to='core.practicearea')),
                ('teams', models.ManyToManyField(blank=True, related_name='wins', to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wins', to=settings.AUTH_USER_MODEL)),
                ('win_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wins', to='core.wintype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
