# Generated by Django 4.2.16 on 2026-01-25 17:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [('core', '0047_win')]

    operations = [
        migrations.CreateModel(
            name='Accomplishment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(db_comment='Title of the accomplishment', help_text='Title of the accomplishment', max_length=255)),
                ('description', models.TextField(db_comment='Detailed description of the accomplishment', help_text='Detailed description of the accomplishment')),
                ('url', models.URLField(db_comment='URL link to the accomplishment', help_text='URL link to the accomplishment')),
                ('accomplished_on', models.DateTimeField(db_comment='Date when the accomplishment was achieved', help_text='Date when the accomplishment was achieved')),
                ('project', models.ForeignKey(db_comment='Project this accomplishment belongs to', help_text='Project this accomplishment belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='accomplishments', to='core.project')),
            ],
        ),
        migrations.AddConstraint(
            model_name='accomplishment',
            constraint=models.UniqueConstraint(fields=('project', 'title'), name='unique_accomplishment_per_project'),
        ),
    ]
