# Generated by Django 4.2.16 on 2025-12-22 21:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [('core', '0048_accomplishment_and_more')]

    operations = [
        migrations.CreateModel(
            name='SocDetailed',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('occ_code', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('soc_broad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soc_detailed', to='core.socbroad')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
