# Generated by Django 4.2.16 on 2025-12-10 00:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_socbroad_socdetailed'),
    ]

    operations = [
        migrations.CreateModel(
            name='SdgTargetIndicator',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('code', models.CharField(max_length=255)),
                ('description_number', models.CharField(max_length=255)),
                ('description_text', models.TextField()),
                ('sdg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sdg_target_indicators', to='core.sdg')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
