# Generated by Django 4.2.16 on 2026-02-05 23:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_sdgtargetindicator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModernJobTitle',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255)),
                ('soc_detailed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modern_job_titles', to='core.socdetailed')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
