# Generated by Django 4.2.16 on 2026-01-28 20:32
import re
import django.contrib.postgres.fields
from django.db import migrations, models


def forward_copy_target_skills(apps, schema_editor):
    """
    Convert existing data from User.target_skills to User.intake_target_skills.
    """
    User = apps.get_model("core", "User")

    for user in User.objects.all().only("uuid", "target_skills", "intake_target_skills"):
        raw = getattr(user, "target_skills", None)

        parsed: list[int] = []

        if raw is None:
            # No data
            parsed = []

        elif isinstance(raw, int):
            # Single integer
            parsed = [raw]

        elif isinstance(raw, (list, tuple)):
            # List values
            try:
                parsed = [int(x) for x in raw if str(x).strip() != ""]
            except Exception:
                parsed = []

        else:
            # String
            s = str(raw).strip()
            if s == "":
                parsed = []
            else:
                parsed = [int(m.group(0)) for m in re.finditer(r"-?\d+", s)]

        # Save into the new ArrayField
        user.intake_target_skills = parsed
        user.save(update_fields=["intake_target_skills"])


class Migration(migrations.Migration):

    dependencies = [('core', '0052_useremploymenthistory')]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='job_title_current_intake',
            new_name='intake_present_job_title',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='job_title_target_intake',
            new_name='intake_target_job_titles',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='slack_id',
            new_name='slack_member_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_status',
            new_name='user_status_type',
        ),
        migrations.AddField(
            model_name='user',
            name='current_target_job_titles',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='current_target_skills',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='intake_present_skills',
            field=models.CharField(blank=True, max_length=255),
        ),
        # Add new intake_target_skills
        migrations.AddField(
            model_name='user',
            name='intake_target_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, size=None),
        ),
        # Convert existing data from target_skills to intake_target_skills
        migrations.RunPython(
            forward_copy_target_skills,
            reverse_code=migrations.RunPython.noop,
        ),
        # Remove old target_skills field
        migrations.RemoveField(
            model_name="user",
            name="target_skills",
        ),
    ]
