# Generated by Django 4.2.27 on 2026-02-20 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_useremploymenthistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='affiliate',
            old_name='partner_logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='affiliate',
            old_name='partner_name',
            new_name='name',
        ),
    ]
