# Generated by Django 4.2.27 on 2026-03-24 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_rename_partner_logo_affiliate_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremploymenthistory',
            name='title',
        ),
        migrations.AddField(
            model_name='useremploymenthistory',
            name='modern_job_title',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_employment_histories', to='core.modernjobtitle'),
            preserve_default=False,
        ),
    ]
