# Generated by Django 4.2.27 on 2026-04-26 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_rename_partner_logo_affiliate_logo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='github_org_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='github_primary_repo_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='google_drive_id',
        ),
        migrations.AddField(
            model_name='project',
            name='completed_on',
            field=models.DateField(blank=True, null=True, verbose_name='Completed on'),
        ),
        migrations.AddField(
            model_name='project',
            name='github_org',
            field=models.ForeignKey(blank=True, help_text='Can be retrieved from gh api with the following: curl -H\n"Authorization: token [gh_PAT]" https://api.github.com/orgs/[org]', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_org', to='core.projecturl'),
        ),
        migrations.AddField(
            model_name='project',
            name='github_primary_repo',
            field=models.ForeignKey(blank=True, help_text='Can be retrieved from gh api with the following:\ncurl -H "Authorization: token [gh_PAT]"\nhttps://api.github.com/repos/[org]/[repo]', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_repo', to='core.projecturl'),
        ),
        migrations.AddField(
            model_name='project',
            name='google_drive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_as_drive', to='core.projecturl'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_leads',
            field=models.ManyToManyField(blank=True, related_name='projects_led', to=settings.AUTH_USER_MODEL),
        ),
    ]
