# Generated by Django 4.2.16 on 2026-06-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_rename_job_title_current_intake_user_intake_present_job_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='intake_target_skills',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
