# Generated by Django 4.2.27 on 2026-05-15 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_location_private'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='affiliation',
            table='core_project_affiliate_xref',
        ),
        migrations.AlterModelTable(
            name='projectstackelementxref',
            table='core_project_stack_element_xref',
        ),
    ]
