# Generated by Django 4.2.27 on 2026-04-29 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0055_location_private')]

    operations = [
        migrations.AddField(
            model_name='faqviewed',
            name='read',
            field=models.IntegerField(default=0),
        ),
    ]
