# Generated by Django 4.2.16 on 2026-06-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('core', '0056_faqviewed_read')]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='job_title_current_intake',
            new_name='intake_present_job_title',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='job_title_target_intake',
            new_name='intake_target_job_titles',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='target_skills',
            new_name='intake_target_skills',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='slack_id',
            new_name='slack_member_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_status',
            new_name='user_status_type',
        ),
        migrations.AddField(
            model_name='user',
            name='current_target_job_titles',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='current_target_skills',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='intake_present_skills',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
