# Generated by Django 4.2.27 on 2026-08-11 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_rename_job_title_current_intake_user_intake_present_job_title_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectStatus',
            new_name='ProjectProgramAreaStatusType',
        ),
        migrations.AlterModelOptions(
            name='projectprogramareastatustype',
            options={'verbose_name_plural': 'project or program area statuses'},
        ),
    ]
