# Generated by Django 4.2.27 on 2026-06-16 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_rename_job_title_current_intake_user_intake_present_job_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='practice_area_secondary',
        ),
        migrations.CreateModel(
            name='UserPracticeAreaSecondaryXref',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('practice_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.practicearea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='practice_area_secondary',
            field=models.ManyToManyField(blank=True, related_name='users_secondary', through='core.UserPracticeAreaSecondaryXref', to='core.practicearea'),
        ),
        migrations.AddConstraint(
            model_name='userpracticeareasecondaryxref',
            constraint=models.UniqueConstraint(fields=('user', 'practice_area'), name='unique_user_practice_area_secondary'),
        ),
    ]
