# Generated by Django 4.2.27 on 2026-08-11 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_rename_projectstatus_projectprogramareastatustype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicearea',
            name='icon',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='practicearea',
            name='leadership_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.leadershiptype'),
        ),
        migrations.AddField(
            model_name='practicearea',
            name='project_program_area_status_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.projectstatus'),
        ),
    ]
