# Generated by Django 4.2.27 on 2026-08-14 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_practicearea_icon_practicearea_leadership_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programarea',
            name='project_program_area_status_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.projectprogramareastatustype'),
        ),
    ]
