# Generated by Django 4.2.27 on 2026-08-21 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_practicearea_icon_practicearea_leadership_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledEvent',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('start_time', models.DateTimeField()),
                ('cancelled_on', models.DateTimeField()),
                ('reason', models.CharField(max_length=255)),
                ('cancelled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
