# Generated by Django 4.2.27 on 2026-08-24 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_practicearea_icon_practicearea_leadership_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stackelement',
            old_name='element_type',
            new_name='stack_element_type',
        ),
    ]
