# Generated by Django 4.2.27 on 2026-08-28 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_rename_element_type_stackelement_stack_element_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPermission',
            new_name='Permission',
        ),
    ]
