# Generated by Django 4.2.27 on 2026-08-28 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_cancelledevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelledevent',
            name='cancelled_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cancelledevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.event'),
        ),
    ]
