# Generated by Django 4.2.27 on 2026-09-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_permission_ended_permission_granted'),
    ]

    operations = [
        migrations.RenameField(
            model_name="affiliation",
            old_name="ended_at",
            new_name="ended",
        ),
        migrations.AlterField(
            model_name="affiliation",
            name="ended",
            field=models.DateField(blank=True, null=True, verbose_name="Ended"),
        ),
    ]
