# Generated by Django 4.2.27 on 2026-09-22 03:30

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_existing_relationships(apps, schema_editor):
    User = apps.get_model("core", "User")
    Xref = apps.get_model("core", "UserPracticeAreaTargetIntakeXref")
    database = schema_editor.connection.alias

    for user in User.objects.using(database).all().iterator():
        for practice_area in user.practice_area_target_intake.all().iterator():
            Xref.objects.using(database).get_or_create(
                user_id=user.pk,
                practice_area_id=practice_area.pk,
            )


def restore_automatic_relationships(apps, schema_editor):
    User = apps.get_model("core", "User")
    Xref = apps.get_model("core", "UserPracticeAreaTargetIntakeXref")
    database = schema_editor.connection.alias

    for relationship in Xref.objects.using(database).all().iterator():
        user = User.objects.using(database).get(pk=relationship.user_id)
        user.practice_area_target_intake.add(relationship.practice_area_id)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_remove_useremploymenthistory_soc_detailed_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPracticeAreaTargetIntakeXref",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="Updated at",
                    ),
                ),
                (
                    "practice_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.practicearea",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            copy_existing_relationships,
            restore_automatic_relationships,
        ),
        migrations.RemoveField(
            model_name="user",
            name="practice_area_target_intake",
        ),
        migrations.AddField(
            model_name="user",
            name="practice_area_target_intake",
            field=models.ManyToManyField(
                blank=True,
                related_name="target_intake_users",
                through="core.UserPracticeAreaTargetIntakeXref",
                to="core.practicearea",
            ),
        ),
        migrations.AddConstraint(
            model_name="userpracticeareatargetintakexref",
            constraint=models.UniqueConstraint(
                fields=("user", "practice_area"),
                name="unique_user_practice_area_target_intake",
            ),
        ),
    ]
