# Generated by Django 4.2.27 on 2026-09-25 22:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_remove_useremploymenthistory_soc_detailed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventOccurrenceChange',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('start_time', models.DateTimeField()),
                ('name_change', models.CharField(null=True)),
                ('description_change', models.CharField(null=True)),
                ('start_time_change', models.DateTimeField(null=True)),
                ('duration_in_min_change', models.IntegerField(null=True)),
                ('video_conference_url_change', models.URLField(null=True)),
                ('additional_info_change', models.TextField(null=True)),
                ('must_attend_change', models.JSONField(default=list, null=True)),
                ('should_attend_change', models.JSONField(default=list, null=True)),
                ('could_attend_change', models.JSONField(default=list, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('location_change', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
