name: PR Checks

on:
  pull_request:

jobs:
  Audit-Pull-Request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4
      - name: Validate mkdocs
        run: |
          docker run --rm -v $(pwd):/app hackforlaops/mkdocs:latest mkdocs build -d /tmp --strict
